### PR TITLE
Try to fix Travis CI builds

### PR DESCRIPTION
**Pull request by AlexWayfer**
:thinking: 

I have no idea for now, on local computer all tests are passing. I'll fix.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Okay, that's what I found out: on local computer `Process.pid` in `Filewatcher#filesystem_updated?` is the same as `@pid` in `ShellWatchRun#start`. But in Travis CI they are different, differ by about 3. And, apparently, sometimes don't get killed and go in parallel. 😣

**Comment by thomasfl** [comment]
Yes, sometimes CI servers suck. I'd simply comment out failing tests for now. If the tests have to be specially tailored to the CI server, then they don't have that much value anyway.

**Comment by AlexWayfer** [comment]
> I'd simply comment out failing tests for now.

The problem is not in failing tests, but in parallelism of unstoppable background processes.

> If the tests have to be specially tailored to the CI server, then they don't have that much value anyway.

I thought how to make them universal and suitable for Travis CI, but now I'm already thinking about switching to Circle CI or another (free CI for OSS) alternative.

**Comment by thomasfl** [comment]
Circle CI looks good. The Circle CI config file let's you config both the machine used to rune the tests and parallelism, and that ought to the trick for the filewatcher tests.

**Comment by AlexWayfer** [comment]
Circle CI has version 1 (similar to Travis CI) and version 2 (based on Docker), but macOS is on beta for version 2, and we need to write to their support for macOS builds, and… it's quite difficult.

-----

OMG, success on Travis CI! :scream:

Just process stopping by process group id.

I'll clear the PR and merge it.

**Comment by thomasfl** [comment]
Do you think you can make all tests pass on Travis CI @AlexWayfer ?

**Comment by AlexWayfer** [comment]
Yes, I'll try. Something rarely breaks in the MRI, and there are problems with the JRuby (reproduced locally).

**Comment by AlexWayfer** [comment]
Main builds are successful, so I'll merge this PR and try to fix JRuby and macOS later. I think there are problems with tests-system, specific for these environments on Travis CI.

JRuby 9.1.9.0 is mostly successful on my local computer.

**Comment by AlexWayfer** [comment]
And `1.0.1` release with crash on file deleting is important.

**Comment by thomasfl** [comment]
Nice! :-)

**Pull request merged**
