### PR TITLE
Option for daemon running added

### LINKED ISSUE #35: Daemonize
Hello!

How can I run `filewatcher` in background?

My case:

```ruby
#!/usr/bin/env ruby

def bash(command)
  system "bash -c \"#{command}\""
end

bash "filewatcher 'some_files' 'some_command' &"
bash "tail -f some_log_file"
```

When I press Ctrl+C in `tail` — `filewatcher` is also stopping.

I want to stop `tail`, but not `filewatcher`.

Thanks!

### PR DESCRIPTION
**Pull request by AlexWayfer**
Resolve #35 

Work's perfectly :+1:

### CODE REVIEW

**Comment by thomasfl** [comment]
Could you please explain what the differences is between running this command

```
   $ filewatcher patterns cmd &
```

and running this command

```
   $ filewatcher --daemonize patterns cmd
```

**Comment by AlexWayfer** [comment]
@thomasfl Yes, of course I tried to explain it [here](https://github.com/thomasfl/filewatcher/issues/35#issuecomment-253256452), but can try again.

`&` make shell job from command (good answer is [here](http://unix.stackexchange.com/questions/86247/what-does-ampersand-mean-at-the-end-of-a-shell-script-line))

And if I call `system 'filewatcher ... &'` from Ruby script, then `system 'tail -f ...'`, and then press `Ctrl+C` in shell — `filewatcher` will be stopped also as `tail`.

I don't know why so and I don't know exactly how it works, to be honest.

But I realized that `&` and `daemon` are different things.

`daemon` is running in the background not at the level of the shell, and at the system level.

You can try make some demo things with `filewatcher` and `tail` from `system` call of Ruby, but I personally got these results.

**Comment by AlexWayfer** [comment]
And I called this option `daemon` (as Ruby API method), not `daemonize`, but I'm not sure what the correct.

**Comment by thomasfl** [comment]
I am afraid to add stuff to filewatcher that can be easily done by other specialized unix command line tools like nohup. I found this on stackoverflow:

"You can daemonize any executable in Unix by using nohup and the & operator:

```
   $ nohup yourScript.sh script args&
```

The nohup command allows you to shut down your shell session without it killing your script, while the & places your script in the background so you get a shell prompt to continue your session. The only minor problem with this is standard out and standard error both get sent to ./nohup.out, so if you start several scripts in this manor their output will be intertwined. A better command would be:

```
  $ nohup yourScript.sh script args >script.out 2>script.error&
```

Source: http://stackoverflow.com/questions/525247/how-do-i-daemonize-an-arbitrary-script-in-unix

We could perhaps add a section in the readme file about running filewatcher in the background and make it  immune to hangups?

**Comment by AlexWayfer** [comment]
Sadly, but no, I've tried `nohup` and it doesn't help. So,

```ruby
system "nohup filewatcher '**/*.{rb,ru,yml}' 'pumactl restart -F config/puma.rb' &"
system 'tail -f log/stdout'
```

`filewatcher` will be stopped when `Ctrl+C` in `tail` output will be pressed. And with `> /dev/null`, and with `-r` option for `filewatcher`.

```
^C./server:21:in `system': Interrupt
	# …
	from ./server:87:in `<main>'
```

**Comment by thomasfl** [comment]
Could you please add a section to the read me with the puma example to explain what it is. Also this may be confused with  the --restart option, so the differences may have to be explained.

**Comment by AlexWayfer** [comment]
It's not only with `puma`:
```ruby
# test.rb
system "nohup filewatcher '**/*' 'echo \"test\"' &"
system 'tail -f test.txt'
```
Ctr+C
```
^Ctest.rb:4:in `system': Interrupt
	from test.rb:4:in `<main>'
$ fish: “nohup filewatcher -d '**/*.{rb,…” terminated by signal SIGTERM (Polite quit request)
```

But OK, I will try to explain something about this in PR for #37

**Pull request merged**
